import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NavBar } from "@/components/Nav";
import { homeConfig } from "@/config/home";
import { getCurrentUser } from "@/lib/session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <body className="min-h-screen font-sans antialiased">
        <header className="sticky top-0 z-40 p-1 border-b bg-background">
          <div className="container mx-auto flex h-16 items-center justify-between py-4">
            <NavBar items={homeConfig} user={user} />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
